version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wiki
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - wiki_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "3333:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgres:postgres
    depends_on:
      - postgres
    networks:
      - wiki_network

networks:
  wiki_network:
    driver: bridge