version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wiki
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: wiki
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./db.init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5430:5430"
    restart: always

volumes:
  db:
    driver: local
