version: '6.0'

services:
  mongodb:
    container_name: mongodb
#    image: mongo
    image: mongodb/mongodb-community-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - wiki_network

networks:
  wiki_network:
    driver: bridge